import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { ArrowLeft, Briefcase, CalendarClock, Mail, MapPin, Phone, User } from "lucide-react";
import { toast } from "sonner";
import { LedgerShell } from "@/components/ledger/LedgerShell";
import { Button } from "@/components/ui/button";
import { metaLeadQuery } from "@/lib/meta-leads-client";
import { convertMetaLead, updateMetaLead } from "@/lib/meta-leads.functions";
import { LEAD_STAGES, type LeadStage } from "@/lib/meta-leads";
import { getAdminToken } from "@/lib/session";
export const Route = createFileRoute("/ledger/leads/$leadId")({ ssr: false, head: () => ({ meta: [{ title: "Lead details — Ledger" }, { name: "description", content: "Review contact details, qualification and lead activity." }, { property: "og:title", content: "Lead details — Ledger" }, { property: "og:description", content: "Review and manage a project lead." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), loader: ({ context, params }) => context.queryClient.ensureQueryData(metaLeadQuery(params.leadId)), component: LeadDetail });
function LeadDetail() {
  const { leadId } = Route.useParams(); const { data } = useSuspenseQuery(metaLeadQuery(leadId)); const lead = data.lead; const qc = useQueryClient(); const navigate = useNavigate(); const update = useServerFn(updateMetaLead); const convert = useServerFn(convertMetaLead); const token = () => { const t = getAdminToken(); if (!t) throw new Error("Admin required"); return t; };
  const change = useMutation({ mutationFn: (stage: LeadStage) => update({ data: { token: token(), id: leadId, stage, qualificationStatus: stage === "Qualified" ? "qualified" : undefined } }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["meta-leads"] }); }, onError: (e: Error) => toast.error(e.message) });
  const win = useMutation({ mutationFn: () => convert({ data: { token: token(), id: leadId } }), onSuccess: async (r) => { await qc.invalidateQueries({ queryKey: ["meta-leads"] }); await qc.invalidateQueries({ queryKey: ["ledger", "jobs"] }); navigate({ to: "/ledger/jobs/$jobId", params: { jobId: r.jobId } }); }, onError: (e: Error) => toast.error(e.message) });
  return <LedgerShell><header className="mb-5"><Button variant="ghost" size="sm" asChild className="-ml-3 mb-3"><Link to="/ledger/leads"><ArrowLeft/>Leads</Link></Button><div className="flex items-start justify-between gap-3"><div><h1 className="display text-[30px] leading-tight">{lead.clientName}</h1><p className="mt-1 text-sm l-muted">{lead.projectType || "Project type needed"}</p></div><span className={`l-chip ${lead.qualificationStatus === "qualified" ? "l-s-active" : lead.qualificationStatus === "rejected" ? "bg-destructive/10 text-destructive" : "l-s-approval"}`}>{lead.qualificationStatus.replace("_", " ")}</span></div></header>
    <section className="l-card-cw p-4"><div className="grid gap-3 text-sm">{lead.phone && <a href={`tel:${lead.phone}`} className="flex items-center gap-3"><Phone className="h-4 w-4 l-muted"/>{lead.phone}</a>}{lead.email && <a href={`mailto:${lead.email}`} className="flex items-center gap-3"><Mail className="h-4 w-4 l-muted"/><span className="truncate">{lead.email}</span></a>}<p className="flex items-start gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 l-muted"/>{lead.address || "Address needed"}</p><p className="flex items-center gap-3"><User className="h-4 w-4 l-muted"/>{lead.assignedOwner || "Unassigned"}</p>{lead.nextAction && <p className="flex items-center gap-3"><CalendarClock className="h-4 w-4 l-muted"/>{lead.nextAction}</p>}</div></section>
    <section className="mt-4"><h2 className="mb-2 text-xs font-bold uppercase l-muted">Stage</h2><div className="flex flex-wrap gap-2">{LEAD_STAGES.map((s) => <Button key={s} size="sm" variant={lead.stage === s ? "default" : "secondary"} className="rounded-full" disabled={change.isPending || (s === "Won" && !lead.ledgerJobId)} onClick={() => s === "Won" ? win.mutate() : change.mutate(s)}>{s}</Button>)}</div>{lead.stage !== "Won" && !lead.ledgerJobId && <p className="mt-2 text-xs l-muted">Choosing Won creates the Ledger job once.</p>}</section>
    <section className="mt-5 grid gap-4 md:grid-cols-2"><div className="l-card p-4"><h2 className="font-bold">Qualification</h2><ul className="mt-2 grid gap-1 text-sm l-muted">{lead.qualificationReasons.map((r) => <li key={r}>• {r}</li>)}</ul>{lead.qualificationStatus !== "qualified" && <Button size="sm" className="mt-4" onClick={() => change.mutate("Qualified")}>Approve manually</Button>}</div><div className="l-card p-4"><h2 className="font-bold">Source</h2><p className="mt-2 text-sm l-muted">{lead.campaign || "Meta lead"}{lead.formName ? ` · ${lead.formName}` : ""}</p><p className="mt-1 text-xs l-muted">Received {new Date(lead.submittedAt ?? lead.importedAt).toLocaleString()}</p></div></section>
    {lead.notes && <section className="l-card mt-4 p-4"><h2 className="font-bold">Notes</h2><p className="mt-2 whitespace-pre-wrap text-sm l-muted">{lead.notes}</p></section>}
    <section className="l-card mt-4 p-4"><h2 className="font-bold">Form answers</h2><dl className="mt-3 grid gap-2">{Object.entries(lead.rawData).map(([k,v]) => <div key={k} className="grid grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] gap-3 border-b l-divider pb-2 text-xs"><dt className="font-bold l-muted">{k}</dt><dd className="break-words">{String(v)}</dd></div>)}</dl></section>
    <section className="mt-5"><h2 className="mb-2 text-xs font-bold uppercase l-muted">Activity</h2><div className="grid gap-2">{data.activity.map((a) => <div key={a.id} className="l-card px-4 py-3"><p className="text-sm font-bold">{a.title}</p>{a.detail && <p className="mt-1 text-xs l-muted">{a.detail}</p>}<p className="mt-1 text-[11px] l-muted">{new Date(a.occurredAt).toLocaleString()}</p></div>)}</div></section>
    {lead.ledgerJobId && <Button asChild className="mt-5 w-full"><Link to="/ledger/jobs/$jobId" params={{ jobId: lead.ledgerJobId }}><Briefcase/>Open Ledger job</Link></Button>}
  </LedgerShell>;
}
