import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { ArrowLeft, Check, ExternalLink } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { LedgerShell } from "@/components/ledger/LedgerShell";
import { Button } from "@/components/ui/button";
import { configureMetaLeadSource, previewMetaLeadSheet, updateMetaQualificationRules } from "@/lib/meta-leads.functions";
import { metaLeadsQuery } from "@/lib/meta-leads-client";
import { LEAD_FIELD_LABELS, type LeadField, type LeadFieldMapping } from "@/lib/meta-leads";
import { getAdminToken } from "@/lib/session";
export const Route = createFileRoute("/ledger/leads/setup")({ ssr: false, head: () => ({ meta: [{ title: "Lead import setup — Ledger" }, { name: "description", content: "Connect and map the Google Sheet used for Meta leads." }, { property: "og:title", content: "Lead import setup — Ledger" }, { property: "og:description", content: "Configure automatic lead importing." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), loader: ({ context }) => context.queryClient.ensureQueryData(metaLeadsQuery()), component: SetupPage });
const FIELDS = Object.keys(LEAD_FIELD_LABELS) as LeadField[];
const split = (v: string) => v.split(",").map((s) => s.trim()).filter(Boolean);
function SetupPage() {
  const { data } = useSuspenseQuery(metaLeadsQuery()); const existing = data.sources[0]; const qc = useQueryClient(); const previewFn = useServerFn(previewMetaLeadSheet); const saveFn = useServerFn(configureMetaLeadSource); const rulesFn = useServerFn(updateMetaQualificationRules);
  const [url, setUrl] = useState(existing?.spreadsheetUrl ?? ""); const [tab, setTab] = useState(existing?.sheetTab ?? ""); const [mapping, setMapping] = useState<LeadFieldMapping>(existing?.fieldMapping ?? {}); const [preview, setPreview] = useState<{ tabs: string[]; headers: string[] } | null>(null); const [budget, setBudget] = useState(data.rules.minimumBudgetCents ? String(data.rules.minimumBudgetCents / 100) : ""); const [types, setTypes] = useState(data.rules.acceptedProjectTypes.join(", ")); const [areas, setAreas] = useState(data.rules.acceptedPostalPrefixes.join(", "));
  const token = () => { const t = getAdminToken(); if (!t) throw new Error("Admin required"); return t; };
  const load = useMutation({ mutationFn: () => previewFn({ data: { token: token(), spreadsheetUrl: url, sheetTab: tab || undefined } }), onSuccess: (r) => { setPreview({ tabs: r.tabs, headers: r.headers }); setTab(r.sheetTab); setMapping((current) => Object.keys(current).length ? current : r.suggestedMapping); }, onError: (e: Error) => toast.error(e.message) });
  useEffect(() => { if (existing && !preview) load.mutate(); }, []);
  const save = useMutation({ mutationFn: async () => { await saveFn({ data: { token: token(), spreadsheetUrl: url, sheetTab: tab, fieldMapping: mapping as Record<string, string>, syncEnabled: true } }); await rulesFn({ data: { token: token(), minimumBudgetCents: budget ? Math.round(Number(budget) * 100) : null, acceptedProjectTypes: split(types), acceptedPostalPrefixes: split(areas) } }); }, onSuccess: async () => { toast.success("Lead import settings saved"); await qc.invalidateQueries({ queryKey: ["meta-leads"] }); }, onError: (e: Error) => toast.error(e.message) });
  return <LedgerShell><header className="mb-6"><Button variant="ghost" size="sm" asChild className="-ml-3 mb-3"><Link to="/ledger/leads"><ArrowLeft/>Leads</Link></Button><h1 className="display text-[32px]">Lead import setup</h1><p className="mt-1 text-sm l-muted">Connect the new Google Sheet and decide which leads qualify automatically.</p></header>
    <section className="grid gap-4"><div className="l-card p-4"><h2 className="font-bold">1. Google Sheet</h2><label className="mt-4 block text-xs font-bold l-muted">Spreadsheet URL<input value={url} onChange={(e) => setUrl(e.target.value)} className="mt-1 h-11 w-full rounded-md border bg-background px-3 text-sm text-foreground" placeholder="https://docs.google.com/spreadsheets/d/…"/></label><Button onClick={() => load.mutate()} disabled={!url || load.isPending} className="mt-3 w-full">{load.isPending ? "Reading…" : "Read sheet"}<ExternalLink/></Button>{preview && <label className="mt-4 block text-xs font-bold l-muted">Sheet tab<select value={tab} onChange={(e) => { setTab(e.target.value); load.mutate(); }} className="mt-1 h-11 w-full rounded-md border bg-background px-3 text-sm text-foreground">{preview.tabs.map((v) => <option key={v}>{v}</option>)}</select></label>}</div>
    {preview && <div className="l-card p-4"><h2 className="font-bold">2. Match columns</h2><p className="mt-1 text-xs l-muted">Name is required. Unavailable fields can stay blank.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{FIELDS.map((field) => <label key={field} className="text-xs font-bold l-muted">{LEAD_FIELD_LABELS[field]}<select value={mapping[field] ?? ""} onChange={(e) => setMapping((m) => ({ ...m, [field]: e.target.value || undefined }))} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm text-foreground"><option value="">Not mapped</option>{preview.headers.map((h) => <option key={h} value={h}>{h}</option>)}</select></label>)}</div></div>}
    <div className="l-card p-4"><h2 className="font-bold">3. Qualification rules</h2><p className="mt-1 text-xs l-muted">Leave any field blank to accept every value.</p><div className="mt-4 grid gap-3"><label className="text-xs font-bold l-muted">Minimum budget<input type="number" min="0" value={budget} onChange={(e) => setBudget(e.target.value)} className="mt-1 h-11 w-full rounded-md border bg-background px-3 text-sm text-foreground" placeholder="50000"/></label><label className="text-xs font-bold l-muted">Accepted project types<input value={types} onChange={(e) => setTypes(e.target.value)} className="mt-1 h-11 w-full rounded-md border bg-background px-3 text-sm text-foreground" placeholder="Kitchen, Basement, Bathroom"/></label><label className="text-xs font-bold l-muted">Postal prefixes or locations<input value={areas} onChange={(e) => setAreas(e.target.value)} className="mt-1 h-11 w-full rounded-md border bg-background px-3 text-sm text-foreground" placeholder="K1A, Ottawa, Nepean"/></label></div></div>
    <Button onClick={() => save.mutate()} disabled={!preview || !mapping.name || save.isPending} className="h-12 w-full">{save.isPending ? "Saving…" : "Save automatic import"}<Check/></Button></section>
  </LedgerShell>;
}
