/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LedgerIndexRouteImport } from './routes/ledger/index'
import { Route as LedgerClosedRouteImport } from './routes/ledger/closed'
import { Route as LedgerActiveRouteImport } from './routes/ledger/active'
import { Route as ApiPublicHooksSheetExportRouteImport } from './routes/api/public/hooks/sheet-export'
import { Route as ApiPublicHooksAutoClockoutRouteImport } from './routes/api/public/hooks/auto-clockout'

const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LedgerRoute,
} as any)
const LedgerClosedRoute = LedgerClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => LedgerRoute,
} as any)
const LedgerActiveRoute = LedgerActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => LedgerRoute,
} as any)
const ApiPublicHooksSheetExportRoute =
  ApiPublicHooksSheetExportRouteImport.update({
    id: '/api/public/hooks/sheet-export',
    path: '/api/public/hooks/sheet-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoClockoutRoute =
  ApiPublicHooksAutoClockoutRouteImport.update({
    id: '/api/public/hooks/auto-clockout',
    path: '/api/public/hooks/auto-clockout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/ledger/active': typeof LedgerActiveRoute
  '/ledger/closed': typeof LedgerClosedRoute
  '/ledger/': typeof LedgerIndexRoute
  '/api/public/hooks/auto-clockout': typeof ApiPublicHooksAutoClockoutRoute
  '/api/public/hooks/sheet-export': typeof ApiPublicHooksSheetExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/ledger/active': typeof LedgerActiveRoute
  '/ledger/closed': typeof LedgerClosedRoute
  '/ledger': typeof LedgerIndexRoute
  '/api/public/hooks/auto-clockout': typeof ApiPublicHooksAutoClockoutRoute
  '/api/public/hooks/sheet-export': typeof ApiPublicHooksSheetExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/ledger/active': typeof LedgerActiveRoute
  '/ledger/closed': typeof LedgerClosedRoute
  '/ledger/': typeof LedgerIndexRoute
  '/api/public/hooks/auto-clockout': typeof ApiPublicHooksAutoClockoutRoute
  '/api/public/hooks/sheet-export': typeof ApiPublicHooksSheetExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apps'
    | '/ledger'
    | '/ledger/active'
    | '/ledger/closed'
    | '/ledger/'
    | '/api/public/hooks/auto-clockout'
    | '/api/public/hooks/sheet-export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apps'
    | '/ledger/active'
    | '/ledger/closed'
    | '/ledger'
    | '/api/public/hooks/auto-clockout'
    | '/api/public/hooks/sheet-export'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apps'
    | '/ledger'
    | '/ledger/active'
    | '/ledger/closed'
    | '/ledger/'
    | '/api/public/hooks/auto-clockout'
    | '/api/public/hooks/sheet-export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppsRoute: typeof AppsRoute
  LedgerRoute: typeof LedgerRouteWithChildren
  ApiPublicHooksAutoClockoutRoute: typeof ApiPublicHooksAutoClockoutRoute
  ApiPublicHooksSheetExportRoute: typeof ApiPublicHooksSheetExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/'
      fullPath: '/ledger/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/ledger/closed': {
      id: '/ledger/closed'
      path: '/closed'
      fullPath: '/ledger/closed'
      preLoaderRoute: typeof LedgerClosedRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/ledger/active': {
      id: '/ledger/active'
      path: '/active'
      fullPath: '/ledger/active'
      preLoaderRoute: typeof LedgerActiveRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/api/public/hooks/sheet-export': {
      id: '/api/public/hooks/sheet-export'
      path: '/api/public/hooks/sheet-export'
      fullPath: '/api/public/hooks/sheet-export'
      preLoaderRoute: typeof ApiPublicHooksSheetExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-clockout': {
      id: '/api/public/hooks/auto-clockout'
      path: '/api/public/hooks/auto-clockout'
      fullPath: '/api/public/hooks/auto-clockout'
      preLoaderRoute: typeof ApiPublicHooksAutoClockoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LedgerRouteChildren {
  LedgerActiveRoute: typeof LedgerActiveRoute
  LedgerClosedRoute: typeof LedgerClosedRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
}

const LedgerRouteChildren: LedgerRouteChildren = {
  LedgerActiveRoute: LedgerActiveRoute,
  LedgerClosedRoute: LedgerClosedRoute,
  LedgerIndexRoute: LedgerIndexRoute,
}

const LedgerRouteWithChildren =
  LedgerRoute._addFileChildren(LedgerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppsRoute: AppsRoute,
  LedgerRoute: LedgerRouteWithChildren,
  ApiPublicHooksAutoClockoutRoute: ApiPublicHooksAutoClockoutRoute,
  ApiPublicHooksSheetExportRoute: ApiPublicHooksSheetExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
