/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksSheetExportRouteImport } from './routes/api/public/hooks/sheet-export'
import { Route as ApiPublicHooksAutoClockoutRouteImport } from './routes/api/public/hooks/auto-clockout'

const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSheetExportRoute =
  ApiPublicHooksSheetExportRouteImport.update({
    id: '/api/public/hooks/sheet-export',
    path: '/api/public/hooks/sheet-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoClockoutRoute =
  ApiPublicHooksAutoClockoutRouteImport.update({
    id: '/api/public/hooks/auto-clockout',
    path: '/api/public/hooks/auto-clockout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ledger': typeof LedgerRoute
  '/api/public/hooks/auto-clockout': typeof ApiPublicHooksAutoClockoutRoute
  '/api/public/hooks/sheet-export': typeof ApiPublicHooksSheetExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ledger': typeof LedgerRoute
  '/api/public/hooks/auto-clockout': typeof ApiPublicHooksAutoClockoutRoute
  '/api/public/hooks/sheet-export': typeof ApiPublicHooksSheetExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ledger': typeof LedgerRoute
  '/api/public/hooks/auto-clockout': typeof ApiPublicHooksAutoClockoutRoute
  '/api/public/hooks/sheet-export': typeof ApiPublicHooksSheetExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ledger'
    | '/api/public/hooks/auto-clockout'
    | '/api/public/hooks/sheet-export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ledger'
    | '/api/public/hooks/auto-clockout'
    | '/api/public/hooks/sheet-export'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ledger'
    | '/api/public/hooks/auto-clockout'
    | '/api/public/hooks/sheet-export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LedgerRoute: typeof LedgerRoute
  ApiPublicHooksAutoClockoutRoute: typeof ApiPublicHooksAutoClockoutRoute
  ApiPublicHooksSheetExportRoute: typeof ApiPublicHooksSheetExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sheet-export': {
      id: '/api/public/hooks/sheet-export'
      path: '/api/public/hooks/sheet-export'
      fullPath: '/api/public/hooks/sheet-export'
      preLoaderRoute: typeof ApiPublicHooksSheetExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-clockout': {
      id: '/api/public/hooks/auto-clockout'
      path: '/api/public/hooks/auto-clockout'
      fullPath: '/api/public/hooks/auto-clockout'
      preLoaderRoute: typeof ApiPublicHooksAutoClockoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LedgerRoute: LedgerRoute,
  ApiPublicHooksAutoClockoutRoute: ApiPublicHooksAutoClockoutRoute,
  ApiPublicHooksSheetExportRoute: ApiPublicHooksSheetExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
